data:
  raw:
    file1: "../data/raw/CC.csv"
    file2: "../data/raw/HU.csv"
    file3: "../data/raw/PP.csv"
    file4: "../data/raw/QQ.csv"
    file5: "../data/raw/RR.csv"
    file6: "../data/raw/SD.csv"
    file7: "../data/raw/SS.csv"
    file8: "../data/raw/TG.csv"
    file9: "../data/raw/TN.csv"
    file10: "../data/raw/TX.csv"
  clean:
    file1: ""